### ISSUE TITLE
Snake returned position is wrong

### ISSUE THREAD

**Issue by shubh261096** [skumailraza/Snakes_and_Ladders#1]
When the player position is equal to snake position then, it is returning the position of player to the ladder down position.

**Comment by 95joel** [comment]
I am getting some fatal exception error when trying to compile the project. Any way to solve this error that i am getting: 
01-29 11:34:50.776 24549-24549/com.example.kumail.game E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.kumail.game, PID: 24549
    java.lang.OutOfMemoryError: Failed to allocate a 110779212 byte allocation with 4194304 free bytes and 52MB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
        at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
        at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:467)
        at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:497)
        at com.example.kumail.game.Ladder.setLadder(Ladder.java:43)
        at com.example.kumail.game.Ladder.<init>(Ladder.java:23)
        at com.example.kumail.game.Board.<init>(Board.java:52)
        at com.example.kumail.game.GameManager.onCreate(GameManager.java:49)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
01-29 11:34:50.780 1568-1892/system_process W/ActivityManager:   Force finishing activity 1 com.example.kumail.game/.GameManager
